### ISSUE TITLE
Search Style Design Feedback

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#36]
- [x] Hyper links need to be color #900000;
- [x] Download button text and icons should be color #774928;
- [x] Column Sorting highlight bar should be color #774928
- [x] Fix highlights on table headers & download button when you click on them 
- [ ] Add date of last update 
- [x] Query tag color, parenthesis color, and Clear button should match the spec 
- [x] Fonts should match design (Headings: Libre Franklin, data and values: open sans - see entity page)
- [x] pagenation needs the HCMI brand colours applied for link/icon colours and active state
 - [x] for the header background, fix the left side of them image so that the lighter colour is showing over the darker right side. This way the logo will always be legible, even on smaller screens/mobile.

https://projects.invisionapp.com/d/main/default/#/console/13747444/286563264/preview
