### ISSUE TITLE
Maintaining selected user value when navigating [# of pages and columns selected]

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#689]
Maintaining selected table length in the catalog/cms when navigating pages
Wiki Specs: https://wiki.oicr.on.ca/display/HCMI/Saved+User+Parameters 

## Implementation details 
- Extend the arranger component interface to accept `<page-size>`, `<table-sorting>`, and `<column-selections>` as properties.  The value should be stored by arranger, in session-storage.
- <Page value>,  `<table-sorting>`, and <column selections> should be stored in session-storage.  This value is managed by arranger, and is default browser behaviour. 
- Update the version of Arranger on the HCMI Searchable Catalog. 

# Expected Behaviour
- [x] When I select the size of a page, then navigate across the portal with various page changes, that number remains the same across different loads. 
- [x]  When I select columns, that view is saved for me when i close/reopen the browser or navigate across pages in the portal. 
- [x] A hard refresh or opening the portal in incognito mode clears all saved parameters.
