### ISSUE TITLE
Unified Bulk Export of Model Details and Variant Data

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#874]
## From the SOW: 
Unified Bulk Export of Model Details and Variant Data 
Currently there is an export button above the Searchable Catalog browsing table; this exports a TSV containing the data values for all models returned by the current query with the columns that the table is displaying. This functionality will be extended to provide a more complete and customizable export, based on whether the user has selected any models for download or not. 
1. Selected Models Export: When a number of models in the table are selected, the Export TSV button will be presented as a dropdown with two options. 
  **a)** The first option will say “N selected models (Column Selection)”, where N is the number of models selected in the table and Column Selection is the exact columns displayed in the table. When clicked, the exported model metadata will only include the fields that are displayed in the table. 
     **b)** The second option will say “N selected models (All Data)”, where N is the number of models selected in the table. When clicked, the exported model metadata will include all available data fields for only the models that have been selected in the table. Column selections will not impact which data is exported. 
2. Default Export: When no models are selected, the default will be to download data for the list of models returned by the current query. The Export TSV button will be presented as a dropdown with two options. 
     **a)** The first option will say “All models (Column Selection)”. When clicked, the exported model metadata will only include the fields that are displayed in the table. 
     **b)** The second option will say “All models (All Data)”. When clicked, the exported model metadata will include all available data fields. Column selections will not impact which data is exported. 
3. Cart Download. The Export TSV in the Cart/Model List will remain visually the same, but will always export the 2b “All models (All Data)” option for all models stored in the cart. 

Exported data will include both model metadata and model variant data. Due to the nature of the data structure, these will need to be packaged differently during the download. The exported data will be a single zip file containing: 
  **a)** A models.tsv TSV file containing model metadata. All models in the selected option will be included in a single file. The file format will be similar to the file that Content Managers use in bulk import. 
  **b)** For each model in the models.tsv document that has variat data, a folder titled after the model name containing 2 separate variant TSVs files: clinical-[model
name].tsv and research-[model name]-[gdc-file-uuid].tsv. The former file will contain data of clinical variants in a similar format to the import file that Content Managers use, while the latter file will contain all data imported from the GDC MAF in a shorter format. If no variants, or no variants of a particular type (clinical or research) are found for a model, no file(s) will be downloaded for that model.
 
To illustrate the organization of files in the zipped package: 
![image](https://user-images.githubusercontent.com/15824252/113726374-31e75c80-96c2-11eb-8a10-74c0a39cfbff.png)

## Steps to execute
- [ ] poc zipping 
- [ ] server side endpoint for models+ variants download \
--- all columns versus selected columns (send a list)
--- list of models OR filter 
--- return's the spec'd zip files 
- [ ] Build download dropdown option UI + styling above the table (replaces the EXPORT ALL button)
- [ ] connect endpoint to the cart button 
- [ ] connect the model_variant_download the search table
