### ISSUE TITLE
Change the calculation of # mutated Genes 

### ISSUE THREAD

**Issue by rosibaj** [nci-hcmi-catalog/portal#946]
##  Requirement 
> The `Most Frequently Mutated Genes` graph on the top right is misleading in that includes `Histological Markers` as well. This was a concern for Daniela, and she wanted to get rid of this confusion by clearer representation of the data shown on the graph. The request is to only combine `#Research Somatic Variant`s + `#Clinical Variants` = `# Mutated Genes`; EXCLUDE #Histological Markers from this equation.

##  Tasks 

- [x] Change the calculation of `# mutated genes` column  `# genes from #Research Somatic Variant`s + `# genes from  #Clinical Variants` = `# Mutated Genes`
- [x] Exclude from count of genes for chart genes where they are only found from the variant classification of histopathological biomarker ONLY 
![image](https://user-images.githubusercontent.com/15824252/130811994-3d0ec909-32c8-4ab4-9470-90d3402e0de5.png)
Table illustrating how these should be added 

| Model has Gene from Research V | Model has Gene from Clinical V  | Model has Gene from Histopathological V | Does this count in the chart?  |
|---|---|---|---|
| TP53 | TP53 | TP53 | Yes, contributes 1 model |
| TP53 | TP53 |  | Yes, contributes 1 model |
|  | TP53 | TP53 | Yes, contributes 1 model |
| TP53 |  |  | Yes, contributes 1 model |
|  | TP53 |  | Yes, contributes 1 model |
|  |  | TP53 | No |

- [x] Add a tooltip to the # Mutated Genes column with the text 
```
The # Mutated Genes is calculated as the intersection of genes  associated to a mutation found in either # Research Variants or # Clinical Variants 
```

**Comment by rosibaj** [comment]
Tested September 27, 2021 

lgtm! thank you @mistryrn
